using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;

public class CircularMinimap : MonoBehaviour
{
    [Header("UI Settings")]
    public float minimapRadius = 150f;
    public Vector2 minimapOffsetFromTopRight = new Vector2(20f, 20f);
    public bool rotateMinimapWithPlayer = true;

    [Header("2D Map Settings (No Camera!)")]
    [Tooltip("Drag your top-down level image here!")]
    public Texture2D mapTexture;
    [Tooltip("The size of the map texture in Unity world units (X and Z)")]
    public Vector2 worldSize = new Vector2(500f, 500f);
    [Tooltip("The center point of the map texture in Unity world units (X and Z)")]
    public Vector2 worldCenterXZ = Vector2.zero;
    [Tooltip("How much of the map to show (0.1 = 10%, 1.0 = whole map)")]
    public float mapZoom = 0.1f;

    private RawImage mapImage;
    private RectTransform mapRect;
    private RectTransform arrowRect;
    private RectTransform markersContainer;

    private struct MapMarker
    {
        public Transform target;
        public RectTransform rect;
    }
    private List<MapMarker> markers = new List<MapMarker>();
    
    // Resource Tracking for Memory Management
    private GameObject _canvasGO;
    private Texture2D _maskTex;
    private Texture2D _gridTex;
    private Texture2D _ringTex;
    private Texture2D _arrowTex;
    private Texture2D _portalTex;
    private Sprite _maskSprite;
    private Sprite _ringSprite;
    private Sprite _arrowSprite;
    private Sprite _portalSprite;
    
    void Start()
    {
        // 0. Auto-load the map texture and bounds generated by the MinimapGenerator
        string sceneName = UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;
        Texture2D loadedMap = Resources.Load<Texture2D>("Minimaps/" + sceneName);
        TextAsset loadedBounds = Resources.Load<TextAsset>("Minimaps/" + sceneName + "_bounds");
        
        if (loadedMap != null && loadedBounds != null)
        {
            mapTexture = loadedMap;
            string[] parts = loadedBounds.text.Split(',');
            if (parts.Length == 4)
            {
                worldSize = new Vector2(float.Parse(parts[0], System.Globalization.CultureInfo.InvariantCulture), float.Parse(parts[1], System.Globalization.CultureInfo.InvariantCulture));
                worldCenterXZ = new Vector2(float.Parse(parts[2], System.Globalization.CultureInfo.InvariantCulture), float.Parse(parts[3], System.Globalization.CultureInfo.InvariantCulture));
            }
        }

        // 1. Create Canvas
        _canvasGO = new GameObject("CircularMinimapCanvas");
        Canvas canvas = _canvasGO.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 100;
        
        // 2. Create Mask Container
        GameObject maskGO = new GameObject("MinimapMask");
        maskGO.transform.SetParent(_canvasGO.transform, false);
        RectTransform maskRect = maskGO.AddComponent<RectTransform>();
        maskRect.anchorMin = new Vector2(1, 1);
        maskRect.anchorMax = new Vector2(1, 1);
        maskRect.pivot = new Vector2(1, 1);
        maskRect.anchoredPosition = -minimapOffsetFromTopRight;
        maskRect.sizeDelta = new Vector2(minimapRadius * 2, minimapRadius * 2);
        
        Image maskImg = maskGO.AddComponent<Image>();
        _maskTex = MakeCircleTex((int)minimapRadius * 2, new Color(0.15f, 0.15f, 0.15f, 1f));
        _maskSprite = Sprite.Create(_maskTex, new Rect(0, 0, minimapRadius * 2, minimapRadius * 2), new Vector2(0.5f, 0.5f));
        maskImg.sprite = _maskSprite;
        Mask mask = maskGO.AddComponent<Mask>();
        mask.showMaskGraphic = true; // Dark background fallback
        
        // 3. Create Map Image
        GameObject mapGO = new GameObject("MinimapImage");
        mapGO.transform.SetParent(maskGO.transform, false);
        mapRect = mapGO.AddComponent<RectTransform>();
        mapRect.anchorMin = new Vector2(0.5f, 0.5f);
        mapRect.anchorMax = new Vector2(0.5f, 0.5f);
        mapRect.pivot = new Vector2(0.5f, 0.5f);
        mapRect.anchoredPosition = Vector2.zero;
        
        // Make it large enough so corners don't show when rotating
        float mapDiam = minimapRadius * 2 * 1.5f; 
        mapRect.sizeDelta = new Vector2(mapDiam, mapDiam);
        
        mapImage = mapGO.AddComponent<RawImage>();
        if (mapTexture != null)
        {
            mapImage.texture = mapTexture;
        }
        else
        {
            _gridTex = MakeGridTex(512, 10);
            mapImage.texture = _gridTex; // Fallback if no texture assigned
        }
        
        // 4. Create Markers Container (Rotates with map)
        GameObject markersGO = new GameObject("MinimapMarkers");
        markersGO.transform.SetParent(maskGO.transform, false);
        markersContainer = markersGO.AddComponent<RectTransform>();
        markersContainer.anchorMin = new Vector2(0.5f, 0.5f);
        markersContainer.anchorMax = new Vector2(0.5f, 0.5f);
        markersContainer.pivot = new Vector2(0.5f, 0.5f);
        markersContainer.sizeDelta = new Vector2(mapDiam, mapDiam);
        markersContainer.anchoredPosition = Vector2.zero;
        
        // 5. Create Ring Border
        GameObject borderGO = new GameObject("MinimapBorder");
        borderGO.transform.SetParent(maskGO.transform, false);
        RectTransform borderRect = borderGO.AddComponent<RectTransform>();
        borderRect.anchorMin = Vector2.zero;
        borderRect.anchorMax = Vector2.one;
        borderRect.sizeDelta = Vector2.zero;
        Image borderImg = borderGO.AddComponent<Image>();
        _ringTex = MakeRingTex((int)minimapRadius * 2);
        _ringSprite = Sprite.Create(_ringTex, new Rect(0, 0, minimapRadius * 2, minimapRadius * 2), new Vector2(0.5f, 0.5f));
        borderImg.sprite = _ringSprite;
        
        // 6. Create Player Arrow
        GameObject arrowGO = new GameObject("MinimapArrow");
        arrowGO.transform.SetParent(maskGO.transform, false);
        arrowRect = arrowGO.AddComponent<RectTransform>();
        arrowRect.anchorMin = new Vector2(0.5f, 0.5f);
        arrowRect.anchorMax = new Vector2(0.5f, 0.5f);
        arrowRect.pivot = new Vector2(0.5f, 0.5f);
        arrowRect.sizeDelta = new Vector2(24, 24);
        Image arrowImg = arrowGO.AddComponent<Image>();
        _arrowTex = MakeArrowTex(32, Color.white);
        _arrowSprite = Sprite.Create(_arrowTex, new Rect(0, 0, 32, 32), new Vector2(0.5f, 0.5f));
        arrowImg.sprite = _arrowSprite;
        
        // 7. Find Portals and create markers for them
        ScenePortal[] portals = FindObjectsByType<ScenePortal>(FindObjectsInactive.Exclude);
        _portalTex = MakeCircleTex(16, new Color(0.8f, 0.2f, 0.8f, 1f));
        _portalSprite = Sprite.Create(_portalTex, new Rect(0,0,16,16), new Vector2(0.5f,0.5f));
        
        foreach (var p in portals)
        {
            GameObject pIcon = new GameObject("PortalMarker");
            pIcon.transform.SetParent(markersContainer, false);
            RectTransform pRect = pIcon.AddComponent<RectTransform>();
            pRect.anchorMin = new Vector2(0.5f, 0.5f);
            pRect.anchorMax = new Vector2(0.5f, 0.5f);
            pRect.pivot = new Vector2(0.5f, 0.5f);
            pRect.sizeDelta = new Vector2(16, 16);
            Image pImg = pIcon.AddComponent<Image>();
            pImg.sprite = _portalSprite;
            
            markers.Add(new MapMarker { target = p.transform, rect = pRect });
        }
    }

    private void OnDestroy()
    {
        if (_canvasGO != null) Destroy(_canvasGO);
        
        if (_maskTex != null) Destroy(_maskTex);
        if (_gridTex != null) Destroy(_gridTex);
        if (_ringTex != null) Destroy(_ringTex);
        if (_arrowTex != null) Destroy(_arrowTex);
        if (_portalTex != null) Destroy(_portalTex);
        
        if (_maskSprite != null) Destroy(_maskSprite);
        if (_ringSprite != null) Destroy(_ringSprite);
        if (_arrowSprite != null) Destroy(_arrowSprite);
        if (_portalSprite != null) Destroy(_portalSprite);
    }

    // Using LateUpdate eliminates jitter because it runs after PlayerMovement and Camera Follow updates are fully complete!
    void LateUpdate()
    {
        if (mapImage == null) return;
        
        // Ensure Bilinear filtering for smooth map movement (eliminates pixel-snapping jaggies)
        if (mapTexture != null && mapTexture.filterMode != FilterMode.Bilinear)
        {
            mapTexture.filterMode = FilterMode.Bilinear;
        }

        // Calculate normalized world position
        float playerNormU = (transform.position.x - worldCenterXZ.x) / worldSize.x + 0.5f;
        float playerNormV = (transform.position.z - worldCenterXZ.y) / worldSize.y + 0.5f;
        
        float uvZoom = mapZoom;
        
        // The rect x,y is the bottom-left corner. We want the player at the center of the uvRect.
        mapImage.uvRect = new Rect(playerNormU - (uvZoom / 2f), playerNormV - (uvZoom / 2f), uvZoom, uvZoom);
        
        float playerAngle = transform.eulerAngles.y;
        float cameraAngle = playerAngle; // fallback
        
        if (Camera.main != null)
        {
            cameraAngle = Camera.main.transform.eulerAngles.y;
        }
        
        if (rotateMinimapWithPlayer)
        {
            // Rotate the map based on the CAMERA, not the player, to prevent snapping jitter!
            mapRect.localRotation = Quaternion.Euler(0, 0, cameraAngle);
            markersContainer.localRotation = Quaternion.Euler(0, 0, cameraAngle);
            
            // The arrow shows which way the player is facing relative to the camera's view
            arrowRect.localRotation = Quaternion.Euler(0, 0, cameraAngle - playerAngle);
        }
        else
        {
            mapRect.localRotation = Quaternion.identity;
            markersContainer.localRotation = Quaternion.identity;
            arrowRect.localRotation = Quaternion.Euler(0, 0, -playerAngle);
        }
        
        // Update markers dynamically
        float mapDiam = minimapRadius * 2 * 1.5f; 
        float fullMapUIPixels = mapDiam / uvZoom;
        
        foreach (var marker in markers)
        {
            if (marker.target == null) continue;
            
            float posNormU = (marker.target.position.x - worldCenterXZ.x) / worldSize.x + 0.5f;
            float posNormV = (marker.target.position.z - worldCenterXZ.y) / worldSize.y + 0.5f;
            
            float deltaU = posNormU - playerNormU;
            float deltaV = posNormV - playerNormV;
            
            // X and Y in the UV space directly translate to UI anchored space relative to center
            float pixelX = deltaU * fullMapUIPixels;
            float pixelY = deltaV * fullMapUIPixels;
            
            marker.rect.anchoredPosition = new Vector2(pixelX, pixelY);
            
            // Counter-rotate markers so they stay upright on the map!
            if (rotateMinimapWithPlayer)
            {
                marker.rect.localRotation = Quaternion.Euler(0, 0, -cameraAngle);
            }
            else
            {
                marker.rect.localRotation = Quaternion.identity;
            }
        }
    }

    private Texture2D MakeCircleTex(int size, Color col)
    {
        Texture2D tex = new Texture2D(size, size);
        float radius = size / 2f;
        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                float dist = Vector2.Distance(new Vector2(x, y), new Vector2(radius, radius));
                tex.SetPixel(x, y, dist <= radius ? col : Color.clear);
            }
        }
        tex.Apply();
        return tex;
    }

    private Texture2D MakeRingTex(int size)
    {
        Texture2D tex = new Texture2D(size, size);
        float radius = size / 2f;
        Color borderCol = new Color(0.8f, 0.8f, 0.8f, 1f);
        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                float dist = Vector2.Distance(new Vector2(x, y), new Vector2(radius, radius));
                if (dist <= radius && dist >= radius - 4f)
                    tex.SetPixel(x, y, borderCol);
                else
                    tex.SetPixel(x, y, Color.clear);
            }
        }
        tex.Apply();
        return tex;
    }

    private Texture2D MakeGridTex(int size, int cells)
    {
        Texture2D tex = new Texture2D(size, size);
        Color bg = new Color(0.15f, 0.15f, 0.15f, 1f);
        Color line = new Color(0.3f, 0.3f, 0.3f, 1f);
        float cellSize = (float)size / cells;
        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                if (x % cellSize < 2 || y % cellSize < 2)
                    tex.SetPixel(x, y, line);
                else
                    tex.SetPixel(x, y, bg);
            }
        }
        tex.wrapMode = TextureWrapMode.Repeat;
        tex.Apply();
        return tex;
    }

    private Texture2D MakeArrowTex(int size, Color col)
    {
        Texture2D tex = new Texture2D(size, size);
        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                float nx = (float)x / size;
                float ny = (float)y / size; 
                
                float halfW = (1f - ny) * 0.4f; 
                
                if (nx >= 0.5f - halfW && nx <= 0.5f + halfW)
                    tex.SetPixel(x, y, col);
                else
                    tex.SetPixel(x, y, Color.clear);
            }
        }
        tex.Apply();
        return tex;
    }
}
